'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _8_Ball_picture_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8_Ball_picture_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _8_Ball_picture_31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8_Ball_picture_31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
